@baseUrl = http://localhost:8080
# @authToken = {{authenticate.response.body.access_token}}

# @name send_file
POST {{baseUrl}}/user/files
Content-Type: application/json
# Authorization: Bearer {{authToken}}

{
    "file": "test.png",
    "path": "user_id"
}

###
